--- #YAML:1.0
name:                Simo
version:             0.02
abstract:            Very simple framework for Object Oriented Perl.
license:             perl
author:              
    - Yuki Kimoto <kimoto.yuki@gmail.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
