---
name: Simo
version: 0.05_06
author:
  - 'Yuki <kimoto.yuki@gmail.com>'
abstract: Very simple framework for Object Oriented Perl.
license: perl
resources:
  license: ~
build_requires:
  Test::More: 0
provides:
  DB:
    file: lib/Simo.pm
  Simo:
    file: lib/Simo.pm
    version: 0.05_06
generated_by: Module::Build version 0.31
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
